version: '3.8'

services:
  db:
    image: mysql:latest
    command: --authentication_policy=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: 172.*.*.*
    ports:
      - "3306:3306"
